---
#------------------------------------------------------------------------------
# Start tasks
#------------------------------------------------------------------------------


  - name: GET VPC INFO
    ec2_vpc_net_facts:
      filters:
        "tag:Name": "{{ vpc_name }}"
        "tag:UK-SE": "{{ uk_se_name }}"
    register: vpc_info


  - name: DEBUG VPC
    debug:
      msg: "{{ vpc_info.vpcs[0].vpc_id }}"


  - name: GET PRIVATE SUBNET INFO
    ec2_vpc_subnet_facts:
      filters:
        vpc-id: "{{ vpc_info.vpcs[0].vpc_id }}"
        "tag:Name": "private"
        "tag:UK-SE": "{{ uk_se_name }}"
    register: private_subnet_info


  - name: DEBUG SUBNET
    debug:
      msg: "{{ private_subnet_info.subnets[0].subnet_id }}"


  - name: SET FACT SUBNET
    set_fact:
      private_subnet_id: "{{ private_subnet_info.subnets[0].subnet_id }}"


  - name: FIND CENTOS AMI
    ec2_ami_facts:
      region: "{{ aws_region }}"
      filters:
        name: "nginx-plus*centos7*v1.1*"
    register: ami_find


  - name: OUTPUT DISCOVERED AMI
    debug:
      msg: "USING AMI: {{ ami_find.images[0].image_id }}"


# Note that idempotency rules mean that 'id' must be unique and not used
# by another instance, even after termination, for 24 hours.
  - name: DEPLOY CENTOS EC2 USING DISCOVERED AMI ID
    ec2:
      id: "{{ app_name }}-{{ centos_app_id }}"
      image: "{{ ami_find.images[0].image_id }}"
      instance_type: t2.micro
      key_name: "{{ sshKey }}"
      wait: yes
      vpc_subnet_id: "{{ private_subnet_id }}"
      group: "private"
      assign_public_ip: yes
      instance_tags:
        Name: "{{ uk_se_name }}-juice-shop"
        UK-SE: "{{ uk_se_name }}"
      user_data: "{{ lookup('file', '../files/ec2_juice_user_data.sh') }}"
    register: ec2


  - name: SET FACT NGINX PRIVATE IP
    set_fact:
      nginx_priv_ip: "{{ ec2.instances[0].private_ip }}"


  - name: SET FACT NGINX PUBLIC IP
    set_fact:
      nginx_pub_ip: "{{ ec2.instances[0].public_ip }}"


  - name: OUTPUT NGINX PUBLIC IP
    debug:
      msg: "{{ nginx_pub_ip }}"

...